Update deprecated type to @type
GoogleCloudPlatform/fluentd-catch-all-config pull request #11
Opened 2017-01-19 15:48 UTC by AmiSMB

2017-04-13 22:53 UTC, igorpeshansky requested changes
I've commented on the content, but unfortunately, we need a CLA before we can proceed.

2017-04-13 22:53 UTC, igorpeshansky commented on pkg/deb/debian/changelog
> +  * Updated deprecated type to @type.
Let's use present tense, for consistency with other comments.

2017-04-27 17:46 UTC, JacobHayes commented
@AmiSMB any update on signing the CLA? Otherwise, @igorpeshansky, could I re-submit this PR with a signed CLA?

2017-07-06 15:53 UTC, AmiSMB commented
I signed it!

2017-07-06 21:29 UTC, igorpeshansky commented
Great, let's address the pending review comments.

2018-01-09 17:18 UTC, igorpeshansky commented
Thanks for the contribution, but I believe this has been superseded by #15.

2018-01-09 17:18 UTC, closed without merging