Update LICENSE
GoogleCloudPlatform/fluentd-catch-all-config pull request #28
Opened 2020-07-23 20:42 UTC by StevenYCChou

Question: should we also backtrace to when the repo was created?

I don't know the answer of the question, so I'll just update the license for users start to use this repositories after this commit, as I think it's reasonable.

2020-07-23 23:09 UTC, igorpeshansky requested changes
The repo was first created in 2014: https://github.com/GoogleCloudPlatform/fluentd-catch-all-config/commits/master/LICENSE. Since that fact is easily traceable through the commit history, we should use the earliest year.

2020-07-23 23:09 UTC, igorpeshansky commented on LICENSE
> +   Copyright 2020- Google, LLC.
The repo was [created in 2014](https://github.com/GoogleCloudPlatform/fluentd-catch-all-config/commits/master/LICENSE), so this should be `Copyright 2014 Google LLC` (or, if you prefer, `Copyright 2014-2020 Google LLC`).

2020-07-24 02:02 UTC, a-robinson commented on LICENSE
> +   Copyright 2020- Google, LLC.
Yup, 2014 would be best. I was working for Google when I created it, so no worries there.

2020-07-24 02:02 UTC, a-robinson requested changes
Yup, 2014 would be best. I was working for Google when I created it, so no worries there.

2020-07-24 04:47 UTC, StevenYCChou commented
Updated, please take another look. Thanks!

2020-07-24 04:57 UTC, igorpeshansky approved these changes
LGTM :shipit:

2020-07-24 12:14 UTC, merged